#!/usr/bin/env python3
'''AYSNC COROUTINE'''
import asyncio
from typing import List


async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    '''returns list of 10 random numbers generated by
    async_generator'''
    return [i async for i in async_generator()]
